# Generated by Django 6.0.4 on 2026-04-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
