# Generated by Django 6.0.4 on 2026-05-02 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_playerprofile_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('component', models.CharField(choices=[('cpu', 'Процессор'), ('motherboard', 'Материнская плата'), ('gpu', 'Видеокарта'), ('ram', 'ОЗУ'), ('storage', 'SSD/HDD'), ('psu', 'Блок питания'), ('cooling', 'Система охлаждения'), ('case', 'Корпус')], max_length=20, verbose_name='Компонент')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='accounts.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
